// Generated by CoffeeScript 1.6.3
(function() {
  var App, Input, Todo, Todos;

  Todo = React.createClass({
    displayName: 'Todo',
    getInitialState: function() {
      return {
        hide: false
      };
    },
    close: function() {
      return this.setState({
        hide: true
      });
    },
    render: function() {
      if (this.state.hide) {
        return null;
      }
      return React.DOM.div({
        classsName: 'todo'
      }, React.DOM.span(null, this.props.text, React.DOM.span({
        onClick: this.close,
        style: {
          float: 'right'
        }
      }, '[x] ')));
    }
  });

  Todos = React.createClass({
    displayName: 'Todos',
    todos: function(todos) {
      return todos.map(function(t) {
        return Todo({
          text: t
        });
      });
    },
    render: function() {
      return React.DOM.div({
        id: "todos"
      }, this.todos(this.props.todos));
    }
  });

  Input = React.createClass({
    displayName: 'Input',
    getInitialState: function() {
      return {
        text: this.props.text
      };
    },
    change: function(e) {
      return this.setState({
        text: e.target.value
      });
    },
    add: function() {
      this.props.add(this.state.text);
      return this.setState({
        text: ""
      });
    },
    render: function() {
      return React.DOM.div(null, React.DOM.input({
        value: this.state.text,
        onChange: this.change
      }, null, React.DOM.button({
        onClick: this.add
      }, 'Add')));
    }
  });

  App = React.createClass({
    displayName: 'App',
    getInitialState: function() {
      return {
        todos: ['first todo']
      };
    },
    add: function(text) {
      this.state.todos.push(text);
      return this.setState({
        todos: this.state.todos
      });
    },
    render: function() {
      return React.DOM.div(null, Input({
        add: this.add
      }), Todos({
        todos: this.state.todos
      }));
    }
  });

  React.renderComponent(App(), document.getElementById('root'));

}).call(this);
